# The OLS Estimator: Theory, Intuition, and Computation
The following notebook explains the OLS estiamtor from both a computational and intuitive perspective. Many students struggle with the mathematics and intuition of the OLS estimator. This notebook provides all of the mathematical and technical details of the OLS estimator along with Python code examples to build intuition for one of the most important algorithms in applied econometrics and data science.

# The Data Generating Process
The data generator processes, or DGP, is the starting point for our investigation into the OLS estimator. The DGP is the model that generates our data and generating our own data can facilitate the analysis of the OLS estimator. 

Another way to think about this is that the research process is the reverse of the DGP process. When engaging in empirical research, we are looking for the most appropriate DGP. In other words, we are looking for a model that could have produced the data that we have at hand. In may cases, we will not be able to completely determine the "true" DGP, however the point is to get as close as possible to the formula that generated the data. In practical terms, this means the choice of explanatory variables that could we make should mimic as closely as possible the DGP. Of course, the choice of which explanatory variables to include in our model is just one choice to be made, but it illustrates how the research process is designed to approximate the true DGP.

# How do we Generate Data?
Generating data from scratch is a fairly simple process, but there are a few decisions that have to be made. First, we need to determine the number of observations we want in our sample, usually denoted by $N$. Next, we need to determine the number of explanatory variables that we would like in our model, usually denoted as $k$. In this lesson, we will use a $k$ that is greater than one, i.e., $k >1$. When $k>1$, we have more than one explanatory variable and thus have a multiple regression model. The multiple regression model can be expressed using matrix algrebra readily, and we will examine these formulas later in the lesson.

First, we need to import Numpy into our Python session. Numpy is a library that adds various matrix and linear algebra routines that are necessary to compute the quantities of interest that we will need later on in the lesson. We can import Numpy with the following command:

In [2]:
import numpy as np
np.random.seed(123)  # This command sets the random seed so that the results here will match your results.


We also import scipy.stats for some of the statistical calculations that we will perform later on:

In [3]:
import scipy.stats as st


Next, we need to specify the number of observations and number of explanatory variables that we will use in our DGP. It should be noted that these choices are arbitrary, and both of these value can be edited and the notebook re-run.

In [4]:
k = 2       # Number of explanatory variables in our regression model (excluding constant--we will get to this later)
N = 1000   # Number of observations in our dataset

The actual regression model indicates that we have $k = 2$ explanatory variables. Mathematically, this is defined as follows:

$y = \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \varepsilon$

The coefficient $\beta_0$ refers to the constant or intercept term, while $\beta_1$ and $\beta_2$ are the coefficients on the two explanatory variables, respectively.

The next step is to generate values for each $X$ variable. The choice of distributional from for these variables is also arbitrary, as the distribution of the explanatory variables has no effect on the estimates of the coefficients  that we obtain from the OLS procedure. In other words, there is no distributional assumption regarding the explanatory variables when using OLS. 

With this caveat in mind, we now generate random values for our explanatory variables. We also need to keep in mind the dimension of the variables we will generate. Usually, the matrix of explanatory variables has dimension $N \times k$ where $N$ is the number of rows in our dataset (i.e.,the number of observations) and $k$ is the number of columns (i.e., the number of variables) in our dataset. You can also think of this matrix of data as an Excel spreadsheet, where we have $N$ rows (observations) and $k$ columns (number of variables).

In this example, we are creating independent $X$'s, which means the correlation between the two variables is zero. We could use a multivariate nomral distribution to generate the explanatory variables with a set correlation between the variables, and the procedure for doing this will be explained in the Conclusion section of this notebook.

Lets generate two random column vectors (with dimension $N \times 1$) to represent the data for our explanatory variables:

In [5]:
x1 = np.random.randn(N).reshape(-1,1)    # reshape(-1,1) reshapes the vector to a column vector

x2 = np.random.randn(N).reshape(-1,1)

Let's print out each of our explanatory variables:

In [6]:
print('The first explanatiory variable:')
print(x1[1:6])

The first explanatiory variable:
[[ 0.99734545]
 [ 0.2829785 ]
 [-1.50629471]
 [-0.57860025]
 [ 1.65143654]]


In [7]:
print('The second explanatory variable:')
print(x2[1:6])

The second explanatory variable:
[[ 0.56759473]
 [ 0.71815054]
 [-0.99938075]
 [ 0.47489832]
 [-1.86849981]]


Regression models usually contain a constant, or intercept term, and we can generate a constant term by creating a Numpy array of ones, like this:

In [8]:
intercept = np.ones(N).reshape(-1,1)    # Intercept term

Now that we have generated the intercept and our two explanatory variables, it is now time to combine all of them into one big matrix $X$. We can accomplish this by horzontially stacking all three vectors toghther:

In [9]:
X = np.hstack((intercept,x1,x2))

We can examine the matrix $X$ and confirm that the first column is the intercept and the other two columns represent our explanatory variables.

In [10]:
print(X[1:6])

[[ 1.          0.99734545  0.56759473]
 [ 1.          0.2829785   0.71815054]
 [ 1.         -1.50629471 -0.99938075]
 [ 1.         -0.57860025  0.47489832]
 [ 1.          1.65143654 -1.86849981]]


Now that we have generated our random data, it's time to choose the $\beta$'s or coefficinets in our model. The multiple regression model is usually written in matrix form as follows:

$y = X \beta + \varepsilon$

We can see that the matrix $X$ is multiplied by our vector of $\beta$'s and these two must conform per the rules of matrix multiplication. The matrix $X$ has dimension $\left(N \times k\right)$ and $\beta$ is a vector of dimension $\left(k \times 1\right)$, which results in a column vector of dimension $\left( N\times 1\right)$. 

This choice for the value of $\beta$ is arbitrary, and we choose the value 3 for each of our coefficients in the following cell:

In [11]:
beta = np.array([3,3,3]).reshape(-1,1)
print(beta)

[[3]
 [3]
 [3]]


We can now examine the $X \beta$ term after performing matrix multiplication:

In [12]:
xb = X@beta
print(xb[1:6])

[[ 7.69482052]
 [ 6.00338712]
 [-4.51702639]
 [ 2.68889421]
 [ 2.34881017]]


We now have to choose the $\varepsilon$, or error term. Recall that in the OLS model and according to the Gauss-Markov Theorem, the distribution of the error term doesn't have any effect on OLS's ability to give us the correct coefficient values. We only need the normality assumption if we wish to perform hypothesis testing.

If we do wish to do hypothesis testing, then we make the assumption that the error term is normally distributed, with mean $0$ and variance $\sigma^2$:

$\varepsilon \sim N\left(0,\sigma^2 \right)$

Let us now generate our random error term. We choose the standard normal distribution, with mean $0$ and standard deviation $1$. Of course, other values for $\sigma^2$ are possible and we illustrate how to do this in the Conclusion section to this notebook.

In [13]:
error = np.random.randn(N,1)
print(error[1:6])

[[-1.20137731]
 [ 1.09625679]
 [ 0.86103685]
 [-1.52036712]
 [-0.44744016]]


Finally, we are ready to generate our dependent variable. Recall that the multiple regression model can be written in matrix form as follows:

$y = X \beta + \varepsilon$

Combining all of the elements that we have so far created, we can now generate our dependent variable.

In [14]:
y = X@beta + error
print(y[1:6])

[[ 6.49344321]
 [ 7.09964391]
 [-3.65598954]
 [ 1.16852709]
 [ 1.90137001]]


Let's take a look at the matrix of generated data:

In [15]:
data = np.hstack((y,X,error))
print(data[1:6])

[[ 6.49344321  1.          0.99734545  0.56759473 -1.20137731]
 [ 7.09964391  1.          0.2829785   0.71815054  1.09625679]
 [-3.65598954  1.         -1.50629471 -0.99938075  0.86103685]
 [ 1.16852709  1.         -0.57860025  0.47489832 -1.52036712]
 [ 1.90137001  1.          1.65143654 -1.86849981 -0.44744016]]


The first column of our "data matrix" is the dependent variable, while columns 2,3, and 4 represent the explanatory variables. The final column is the error term. We can calculate the first value of the dependent variable using the following values:

In [16]:
print(data[1,1:])

[ 1.          0.99734545  0.56759473 -1.20137731]


In [17]:
print(3*data[1,1] + 3*data[1,2] + 3*data[1,3] + data[1,4]) # We multiply the intercept term and two explanatory variables by 3.


6.4934432121296


You'll notice that our "by hand" calculation of the first value of the dependent vaariable matches what we calculated via matrix algebra. Instead of doing all of these calculations by hand, matrix algebra allows one to perform these calculations regardless of the size of the dataset, which is extremely convenient!

# The OLS Estimator

We now turn our attention to the OLS estimator. Although we will not formally derive the formula for the OLS estimator, the formula is as follows:

$\hat \beta  = {\left( {X'X} \right)^{ - 1}}X'y$

The formula above returns the vector of $\hat \beta$ coefficients estimated from our generated data and has dimension $\left(k \times 1\right)$, i.e., one coefficient for each explanatory variable, including the constant term. Let's calculate this quantity in Python:

In [18]:
beta_hat = np.linalg.inv(X.T@X)@X.T@y
print(beta_hat)

[[3.00920206]
 [2.9677746 ]
 [2.98522671]]


Recall that the $\beta$'s we used in generating the data were all set to the value 3, so we should expect to see this value when we calculate the coefficeints "by hand". You'll note that the estimates from the formula above are very close to the true values that we used to generate the data. It appears that our "by hand" OLS calculations are very accurate.

In empirical research, we never truly know the true data generating process and the goal is to try and mimic this unknown linear function using regression techniques. The beauty of generating our own data is that we can use all of the formulas used in OLS and calculate everything "by hand" and examine each quantity to see how all of the pieces fit together. 

We have calculated our coefficients but what about statistical significance? We now turn our attention to this topic.

# Hypothesis Testing

Hypothesis testing is an important part of regression modeling and it is important to see how we can calculate all of the quantities using the standard formulas.

One of the first quantitities that needs to be calculated are the residuals from our regression model. Recall that the residuals are calculated as follows:

$\hat ɛ = y - \hat y$

where $y$ is the actual value of the dependent variable and $\hat y$ is the predicted value of $y$ from our regression model. The predicted values are those values that our model predicts for each value of the explantory variables. Predicted values in our regression model are clauclated as follows:

$X  \hat \beta$

where $\hat \beta$ are the regression coefficients calculated via OLS. We can rewrite the formula above to include this information:

$\hat ɛ = y - X \hat \beta$

The residuals need to be calcualted so that we may obtain an estimate of $\hat \sigma^2$. The quantity $\hat \sigma^2$ is used to obtain the standard errors of our regression coefficients.



An important concept in regression modeling is the idea of a sampling distribution. The basic idea is that whenever we engage in empirical research, we obtain one possible dataset out of many possible datasets that could have been collected. For example, the dataset that we obtain could have been collected the day before or the day after, or any other day. If we were to run a separate regression for each dataset that we collect, we would obtain different estimates for the regression coefficients and these coefficients would have a distribution, referred to as the sampling distribution of the OLS estimator. 

Given that the regressions we run from different datasets that we could have collected form a distribution of coefficeints (i.e., a separate distribution for each coefficient), that sampling distribution of the OLS estimates would also have a standard deviation, which is a measure of how confident we are in the coefficient estimates. A small standard deviation means that the coefficients have been estimated fairly accurately, while a large standard deviation means that the coefficients have been estimated with higher uncertainty. The standard deviation of the sampling disrtibution of the regression coefficients can be affected by the sample size of the data (larger sample sizes decrease the standard error), the value of $\hat \sigma^2$ (how tightly grouped the data are around the regression line--smaller values are better), and the variation in our explanatory variable, where more variation is preferred.

The formula for calculating the standard error of the regression coefficients is referred to as the variance-covariance matrix. The VC matrix is a $\left(k \times k \right)$ matrix, where the diagonal elements are the variances of the sampling distributons of the coefficient estimates. The formula for the VC matrix is as follows:

$VC_{\hat \beta} = \hat \sigma {\left( {X'X} \right)^{ - 1}}$

where $\hat \sigma^2$ is an estimate of the true value $\sigma^2$. Since we do not know the true value of $\sigma^2$, we have to estimate it from the data.

The formula for calcualting the value of $\hat \sigma^2$ is as follows:

$\hat \sigma ^2 = \frac{{\varepsilon'\varepsilon }}{{N - k}}$

Note that $\hat \sigma^2$ will be a scalar, i.e., a single number. Recall that $\varepsilon$ is a $\left(N \times 1\right)$ vector and it's transpose is a $\left(1 \times N\right)$ vector. When we multiply the transposed $\left(1 \times N\right)$ vector of residuals by the original $\left(N \times 1\right)$ vector of residuals, we obtain a $\left(1 \times 1\right)$ "matrix" or single number, which is referred to as a scalar.  

Let's calculate this quantity in Python:

In [19]:
residual = y - X@beta_hat   #Calculate residual

sigma_2 = (residual.T@residual)/(N-k)

print(f'Our estimate of sigma squared is :{sigma_2}')

Our estimate of sigma squared is :[[0.96397663]]


You'll note that since we created our error term from a $N\left(0,1 \right)$ standard normal distribution, our estimate of $\sigma^2$ is close to the true value of 1.

Since we now have all of the elements to calculate the VC matrix, let's do so in Python:

In [20]:
VC = sigma_2*np.linalg.inv(X.T@X)
print(VC)

[[ 9.65537757e-04  3.78520768e-05 -7.57439553e-06]
 [ 3.78520768e-05  9.63402925e-04  3.14843680e-05]
 [-7.57439553e-06  3.14843680e-05  1.05136147e-03]]


The diagonal elements of the VC matrix are the variances of the sampling distributions of the OLS estimator. Element (1,1) is the variance for the intercept, while element (2,2) and element (3,3) are the variances for explanatory variables 2 and 3, respectively. 

In reality, we actually need the standard deviation of these estimates in order to calculate the t-statistics needed for hypothesis testing, which requires taking the square root of the diagonal elements.

We can calculate the standard deviation of the sampling distribution of the OLS estimator in Python as follows:

In [31]:
VC_diagonal = np.sqrt(np.diag(VC)).reshape(k+1,1)
print(VC_diagonal)

[[0.0310731 ]
 [0.03103873]
 [0.0324247 ]]


The t-statistics needed for hypothesis testing are simply the values of the estimated coefficients divided by their respective standard errors.

Calculating these t-statistics can be accomplished in Python as follows:

In [22]:
t_stats = beta_hat/VC_diagonal
print(t_stats)

[[96.84266211]
 [95.61519896]
 [92.06642739]]


Since we now have calculated our t-statistics, we can find their associated p--values:

In [23]:
p_values = st.t.sf(abs(t_stats), df=N-k-1)*2    # Multiply by 2 for a 2 sided test
print(p_values)


[[0.]
 [0.]
 [0.]]


The final entry in our "table" of results are the lower and upper 95% confidence intervals. Recall from basic statistics that the 95% confidence interval for our coefficient estimate can be calculated as follows:

$\hat \beta \pm t_{critical} \times \operatorname{SE} \left(\hat \beta\right)$

We first need to calculate the critical value, and we assume $\alpha = 0.05$, which we divide by two in the function call since we are assuming a two-tailed test:

In [24]:
t_critical = st.t.ppf(q=1-.05/2,df=N-k-1)
print(t_critical)

1.962346236089449


Next, we calculate both the lower and upper bound to obtain the 95% confidence intervals for our coefficient estimates:

In [25]:
t_critical = np.abs(t_critical)
lower95 = beta_hat - t_critical*VC_diagonal     # t-critical is the critical value from the t-distribution
upper95 = beta_hat + t_critical*VC_diagonal     # VC_diagonal are the SE's for each coefficient

print('The lower 95% intervals:')
print(lower95)
print('The upper 95% intervals')
print(upper95)

The lower 95% intervals:
[[2.94822587]
 [2.90686586]
 [2.92159821]]
The upper 95% intervals
[[3.07017824]
 [3.02868334]
 [3.04885521]]


All of the quantities that we have calculated are spread out over this notebok and it's extremely convenient to collect all of these quantities in a pandas Data Frame for easy viewing.

We first import pandas and then create a Data Frame with all of our information:

In [26]:
import pandas as pd

table = np.hstack([beta_hat, VC_diagonal, t_stats,p_values,lower95,upper95])

df = pd.DataFrame(table, index = ['Intercept','X1', 'X2'], columns = ['Coef.', 'Std. Error', 't-stat','p-value','Lower 95%', 'Upper 95%'])

results_dataframe = df.round(decimals=3)    #Round values for easy reading

results_dataframe


Coef.  Std. Error  t-stat  p-value  Lower 95%  Upper 95%
Intercept  3.009       0.031  96.843      0.0      2.948      3.070
X1         2.968       0.031  95.615      0.0      2.907      3.029
X2         2.985       0.032  92.066      0.0      2.922      3.049

# Verification of Our Results

Obviously, it is inconvenient to calculate all of these statistics by hand (but certaily educational!). Also, it's important to compare our results to an established routine to make sure that we have calcualted everything correctly.

We can use the Python package statsmodels to perform a linear regression and compare the results from that routine to the results in our table above.

We first import that statsmodel package:

In [27]:
import statsmodels.api as sm


Next, we call the OLS function and print out the results:

In [28]:
model = sm.OLS(y, X).fit()

print_model = model.summary()

print(print_model)

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.945
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     8534.
Date:                Fri, 08 Jul 2022   Prob (F-statistic):               0.00
Time:                        09:42:39   Log-Likelihood:                -1399.6
No. Observations:                1000   AIC:                             2805.
Df Residuals:                     997   BIC:                             2820.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.0092      0.031     96.794      0.0

If we compare the results calculated in this notebook to the statsmodels results, we see that they are almost exactly the same, subject to rounding error.

# Conclusion


The matrix formulation of the OLS routine is a convenient manner in which to calculate the quantities that we normally see from "black box" regression software. This notebook is designed to demystify this process to see how these calculations are done "by hand" so that students of regression modeling can build intuition regarding how the mathematics translates into Python code.

We encourage students to explore this notebook and change some of the quantities to see how these changes affect the OLS estimator. Suggestions include the following:

* Decrease the number of observations in the notebook to $N = 25$. How does the decrease in sample size affect the estimates?
* Change the standard deviation of the error term using this code:
```
    n = 100
    error = np.random.randn(N,1)*np.sqrt(n) # The n here is the standard deviation of the error term, not the sample size.
```
How does incresing the standard deviation of the error term affect the coefficient estimates, if at all? Does it change the significance of the coefficient estimates?
* The explanatory variables can be generated from a multivariate normal distribution with the folloiwng code:
  
  ```
  mean = np.zeros(2)  # The number of explanatory variable is two, and their mean is zero.
  covariance = np.array([[1, .8],
                        [.8,1]])
  X = np.random.multivariate_normal(mean, covariance,N).reshape(N,2)
  ```
In this code snippet, we are generating two explanatory variables from a multivariate normal distribution with a mean of zero and standard deviation of 1 (which are on the diagonal of the covariance matrix). Note that the covariance matrix for these random draws is set to 0.8, which indicates that the two variables have a correlation of $\rho = 0.8$ (the off-diagonal elements of the covariance matrix).

Try adjusting the correlation to a large number such as $\rho = 0.99$. What effect does this have on the model estimates? What happens if we set $\rho =1$?

* Increase the dispersion of the explantory variables generated by using the following code:
```
  x1 = np.random.randint(0,500,N).reshape(-1,1)
  x2 = np.random.randint(0,500,N).reshape(-1,1)
```
The original code generated the x1 and x2 variables from a standard normal distribution with a mean of 0 and standard deviation of 1. The above code generates a random x1 and x2 from a uniform distribution of integers with a range from 0 to 500. Explore by changing the upper bound to 10, which restricts the dispersion of the explanatory variables. How does this affect the estimates?